version: "3.8"
services:
  chisso-app:
    build: .
    container_name: chisso-auction-platform-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=elisabetta
      - DB_NAME=auction_platform
    depends_on:
      - chisso-mysql

  chisso-mysql:
    image: mysql:8.0
    container_name: chisso-auction-platform-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elisabetta
      MYSQL_DATABASE: auction_platform
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
